// LocalCurrency.ts

import { Universities } from "../../assets/Universities";
import { CustomUser } from "../../types";

// Define the type for currency symbols
type CurrencySymbols = {
  [key: string]: string;
};

const currencySymbols: CurrencySymbols = {
  Afghanistan: "؋",
  Albania: "L",
  Algeria: "دج",
  Andorra: "€",
  Angola: "Kz",
  Argentina: "$",
  Armenia: "֏",
  Australia: "$",
  Austria: "€",
  Azerbaijan: "₼",
  Bahamas: "$",
  Bahrain: ".د.ب",
  Bangladesh: "৳",
  Barbados: "$",
  Belarus: "Br",
  Belgium: "€",
  Belize: "$",
  Benin: "CFA",
  Bhutan: "Nu.",
  Bolivia: "Bs.",
  "Bosnia and Herzegovina": "KM",
  Botswana: "P",
  Brazil: "R$",
  Brunei: "$",
  Bulgaria: "лв",
  "Burkina Faso": "CFA",
  Burundi: "FBu",
  Cambodia: "៛",
  Cameroon: "CFA",
  Canada: "$",
  "Cape Verde": "$",
  "Central African Republic": "CFA",
  Chad: "CFA",
  Chile: "$",
  China: "¥",
  Colombia: "$",
  Comoros: "CF",
  "Congo (Brazzaville)": "CFA",
  "Congo (Kinshasa)": "FC",
  "Costa Rica": "₡",
  Croatia: "kn",
  Cuba: "₱",
  Cyprus: "€",
  "Czech Republic": "Kč",
  Denmark: "kr",
  Djibouti: "Fdj",
  Dominica: "$",
  "Dominican Republic": "RD$",
  Ecuador: "$",
  Egypt: "£",
  "El Salvador": "$",
  "Equatorial Guinea": "CFA",
  Eritrea: "Nfk",
  Estonia: "€",
  Eswatini: "E",
  Ethiopia: "ብር",
  Fiji: "$",
  Finland: "€",
  France: "€",
  Gabon: "CFA",
  Gambia: "D",
  Georgia: "₾",
  Germany: "€",
  Ghana: "₵",
  Greece: "€",
  Grenada: "$",
  Guatemala: "Q",
  Guinea: "FG",
  "Guinea-Bissau": "CFA",
  Guyana: "$",
  Haiti: "G",
  Honduras: "L",
  Hungary: "Ft",
  Iceland: "kr",
  India: "₹",
  Indonesia: "Rp",
  Iran: "﷼",
  Iraq: "ع.د",
  Ireland: "€",
  Israel: "₪",
  Italy: "€",
  Jamaica: "$",
  Japan: "¥",
  Jordan: "د.ا",
  Kazakhstan: "₸",
  Kenya: "Sh",
  Kiribati: "$",
  "Korea (North)": "₩",
  "Korea (South)": "₩",
  Kuwait: "د.ك",
  Kyrgyzstan: "лв",
  Laos: "₭",
  Latvia: "€",
  Lebanon: "ل.ل",
  Lesotho: "L",
  Liberia: "$",
  Libya: "ل.د",
  Liechtenstein: "CHF",
  Lithuania: "€",
  Luxembourg: "€",
  Madagascar: "Ar",
  Malawi: "MK",
  Malaysia: "RM",
  Maldives: "Rf",
  Mali: "CFA",
  Malta: "€",
  "Marshall Islands": "$",
  Mauritania: "UM",
  Mauritius: "₨",
  Mexico: "$",
  Micronesia: "$",
  Moldova: "L",
  Monaco: "€",
  Mongolia: "₮",
  Montenegro: "€",
  Morocco: "د.م.",
  Mozambique: "MT",
  Myanmar: "K",
  Namibia: "$",
  Nauru: "$",
  Nepal: "₨",
  Netherlands: "€",
  "New Zealand": "$",
  Nicaragua: "C$",
  Niger: "CFA",
  Nigeria: "₦",
  Norway: "kr",
  Oman: "ر.ع.",
  Pakistan: "₨",
  Palau: "$",
  Panama: "B/.",
  "Papua New Guinea": "K",
  Paraguay: "₲",
  Peru: "S/",
  Philippines: "₱",
  Poland: "zł",
  Portugal: "€",
  Qatar: "ر.ق",
  Romania: "lei",
  Russia: "₽",
  Rwanda: "FRw",
  "Saint Kitts and Nevis": "$",
  "Saint Lucia": "$",
  "Saint Vincent and the Grenadines": "$",
  Samoa: "T",
  "San Marino": "€",
  "Sao Tome and Principe": "Db",
  "Saudi Arabia": "ر.س",
  Senegal: "CFA",
  Serbia: "дин",
  Seychelles: "₨",
  "Sierra Leone": "Le",
  Singapore: "$",
  Slovakia: "€",
  Slovenia: "€",
  "Solomon Islands": "$",
  Somalia: "Sh",
  "South Africa": "R",
  "South Sudan": "£",
  Spain: "€",
  "Sri Lanka": "Rs",
  Sudan: "ج.س.",
  Suriname: "$",
  Sweden: "kr",
  Switzerland: "CHF",
  Syria: "£",
  Taiwan: "NT$",
  Tajikistan: "ЅМ",
  Tanzania: "Sh",
  Thailand: "฿",
  "Timor-Leste": "$",
  Togo: "CFA",
  Tonga: "T$",
  "Trinidad and Tobago": "TT$",
  Tunisia: "د.ت",
  Turkey: "₺",
  Turkmenistan: "T",
  Tuvalu: "$",
  Uganda: "Sh",
  Ukraine: "₴",
  "United Arab Emirates": "د.إ",
  "United Kingdom": "£",
  "United States": "$",
  Uruguay: "$U",
  Uzbekistan: "сўм",
  Vanuatu: "VT",
  "Vatican City": "€",
  Venezuela: "Bs.S",
  Vietnam: "₫",
  Yemen: "﷼",
  Zambia: "ZK",
  Zimbabwe: "$",
};

const getLocalCurrency = (customUser: CustomUser): string => {
  if (!customUser) return "";

  const uni = Universities.find((uni) => uni.name.includes(customUser.school));

  if (!uni) return "";

  const localCountry = uni.country;

  if (!localCountry) return "";

  return currencySymbols[localCountry] || "";
};

export default getLocalCurrency;
