export const themes = {
  theme1: {
    royalBlue: "#0A2463",
    celestialBlue: "#3E92CC",
    ghostWhite: "#FFFAFF",
    cerise: "#D8315B",
    smallListing: "#e9e7e9",
    tan: "#E8E4DF",
    turquoise: "#8dc3b3",
  },
  theme2: {
    royalBlue: "#273db4",
    celestialBlue: "blue",
    ghostWhite: "#dbd39f",
    cerise: "#ed7845",
    smallListing: "#f95ca4",
    tan: "#F8F4EF",
    turquoise: "#9dc3c3",
  },
  theme3: {
    royalBlue: "#2A4163",
    celestialBlue: "#6EA9CC",
    ghostWhite: "#EFFAFF",
    cerise: "#F8535B",
    smallListing: "#faf7f9",
    tan: "#F4E4EF",
    turquoise: "#adc3c3",
  },
  theme4: {
    royalBlue: "#3A5163",
    celestialBlue: "#7EB3CC",
    ghostWhite: "#DFFAFF",
    cerise: "#FF635B",
    smallListing: "#fbf7f9",
    tan: "#E4E4EF",
    turquoise: "#bdc3c3",
  },
};
